2022-03-10 10:38:03 [scrapy.utils.log] INFO: Scrapy 2.5.1 started (bot: Crawl_hyx)
2022-03-10 10:38:03 [scrapy.utils.log] INFO: Versions: lxml 4.7.1.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.1.0, Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)], pyOpenSSL 22.0.0 (OpenSSL 1.1.1m  14 Dec 2021), cryptography 36.0.1, Platform Windows-10-10.0.19044-SP0
2022-03-10 10:38:03 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2022-03-10 10:38:03 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'Crawl_hyx',
 'LOG_FILE': 'log/scrapy_2022_3_10_3.log',
 'NEWSPIDER_MODULE': 'Crawl_hyx.spiders',
 'SPIDER_MODULES': ['Crawl_hyx.spiders']}
2022-03-10 10:38:03 [scrapy.extensions.telnet] INFO: Telnet Password: 5edb0d54000c02c5
2022-03-10 10:38:03 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2022-03-10 10:38:04 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless", "--disable-gpu", "--no-sandbox", "--headless"]}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless", "--disable-gpu", "--no-sandbox", "--headless"]}}}
2022-03-10 10:38:04 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): localhost:64646
2022-03-10 10:38:05 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session HTTP/1.1" 200 797
2022-03-10 10:38:05 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:05 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/timeouts {"implicit": 1000}
2022-03-10 10:38:05 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/timeouts HTTP/1.1" 200 14
2022-03-10 10:38:05 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:05 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'Crawl_hyx.middlewares.CrawlHyxDownloaderMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-03-10 10:38:05 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-03-10 10:38:05 [scrapy.middleware] INFO: Enabled item pipelines:
['Crawl_hyx.pipelines.WanyiPipeline', 'Crawl_hyx.pipelines.ImagePipeline']
2022-03-10 10:38:05 [scrapy.core.engine] INFO: Spider opened
2022-03-10 10:38:05 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 10:38:05 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-03-10 10:38:05 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://war.163.com/> from <GET http://war.163.com/>
2022-03-10 10:38:05 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/"}
2022-03-10 10:38:08 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:08 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:10 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:10 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 438673
2022-03-10 10:38:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/> (referer: None)
2022-03-10 10:38:10 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/"}
2022-03-10 10:38:11 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:11 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:11 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "return document.body.scrollHeight;", "args": []}
2022-03-10 10:38:11 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 15
2022-03-10 10:38:11 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:13 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:13 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:15 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:15 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:15 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:17 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:17 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:17 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:19 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:19 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:21 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:21 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:21 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:23 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 10:38:23 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 14
2022-03-10 10:38:23 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:23 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/execute/sync {"script": "return document.body.scrollHeight;", "args": []}
2022-03-10 10:38:23 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/execute/sync HTTP/1.1" 200 15
2022-03-10 10:38:23 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:24 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313500.html"}
2022-03-10 10:38:26 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:26 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:28 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:28 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 132041
2022-03-10 10:38:28 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313500.html> (referer: https://war.163.com/)
2022-03-10 10:38:28 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313501.html"}
2022-03-10 10:38:29 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:29 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:31 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:31 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 135200
2022-03-10 10:38:31 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:31 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313501.html> (referer: https://war.163.com/)
2022-03-10 10:38:31 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20NED830514R9OJ.html"}
2022-03-10 10:38:32 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:32 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:34 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:35 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 309512
2022-03-10 10:38:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:35 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20NED830514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:38:35 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H2117GQ00514R9OJ.html"}
2022-03-10 10:38:35 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:37 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:37 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 234969
2022-03-10 10:38:37 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2117GQ00514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:38:37 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/war/article/H21DGSJI000181KT.html"}
2022-03-10 10:38:38 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:38 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:40 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:41 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 293926
2022-03-10 10:38:41 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H21DGSJI000181KT.html> (referer: https://war.163.com/)
2022-03-10 10:38:41 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1V4J10B05504DOH.html"}
2022-03-10 10:38:41 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:41 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:43 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:43 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 243053
2022-03-10 10:38:43 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1V4J10B05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:38:43 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20NEDKS0514R9OJ.html"}
2022-03-10 10:38:44 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:44 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:46 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:46 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 246350
2022-03-10 10:38:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20NEDKS0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:38:46 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20KD22N0514R9OJ.html"}
2022-03-10 10:38:47 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:47 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:49 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:49 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 257235
2022-03-10 10:38:49 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:49 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20KD22N0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:38:49 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20S7UTJ05504DOH.html"}
2022-03-10 10:38:50 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:52 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:52 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 248623
2022-03-10 10:38:52 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20S7UTJ05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:38:52 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20J6EVG0514R9OJ.html"}
2022-03-10 10:38:53 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:53 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:55 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:55 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 255131
2022-03-10 10:38:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20J6EVG0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313500.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313501.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20NED830514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2117GQ00514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H21DGSJI000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1V4J10B05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20NEDKS0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20KD22N0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20S7UTJ05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:38:55 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H212CHE805504DOH.html"}
2022-03-10 10:38:56 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:56 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:58 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:38:58 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 255317
2022-03-10 10:38:58 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:38:58 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H212CHE805504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:38:58 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1VHH5V105504DOH.html"}
2022-03-10 10:38:59 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:38:59 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:01 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:01 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 245762
2022-03-10 10:39:01 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:01 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1VHH5V105504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:39:01 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313498.html"}
2022-03-10 10:39:02 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:02 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:04 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:04 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 158249
2022-03-10 10:39:04 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313498.html> (referer: https://war.163.com/)
2022-03-10 10:39:04 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313502.html"}
2022-03-10 10:39:04 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:04 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:06 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:06 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 115163
2022-03-10 10:39:06 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:06 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313502.html> (referer: https://war.163.com/)
2022-03-10 10:39:06 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/war/article/H20T63UV000181KT.html"}
2022-03-10 10:39:08 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:08 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:10 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:10 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 321949
2022-03-10 10:39:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H20T63UV000181KT.html> (referer: https://war.163.com/)
2022-03-10 10:39:10 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H22ILAC20514R9OJ.html"}
2022-03-10 10:39:11 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:11 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:13 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:13 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 197307
2022-03-10 10:39:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22ILAC20514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:13 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313497.html"}
2022-03-10 10:39:14 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:14 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:16 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:16 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 140979
2022-03-10 10:39:16 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:16 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313497.html> (referer: https://war.163.com/)
2022-03-10 10:39:16 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html"}
2022-03-10 10:39:17 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:17 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:19 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:19 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 231911
2022-03-10 10:39:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:19 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:19 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1UG7CBL05504DOH.html"}
2022-03-10 10:39:19 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:21 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:21 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 257895
2022-03-10 10:39:21 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:21 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1UG7CBL05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:39:21 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1UGDNNO0514R9OJ.html"}
2022-03-10 10:39:23 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:23 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:25 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:25 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 249826
2022-03-10 10:39:25 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1UGDNNO0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:25 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1U4MISN0514R9OJ.html"}
2022-03-10 10:39:26 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:26 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:28 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:28 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 260931
2022-03-10 10:39:28 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1U4MISN0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:28 [scrapy.extensions.logstats] INFO: Crawled 22 pages (at 22 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20J6EVG0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H212CHE805504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1VHH5V105504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313498.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313502.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H20T63UV000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22ILAC20514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313497.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1UGDNNO0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1UG7CBL05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:28 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html"}
2022-03-10 10:39:30 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:30 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:32 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:32 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 262016
2022-03-10 10:39:32 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:32 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/war/article/H1UBH5N5000181KT.html"}
2022-03-10 10:39:34 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:34 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:36 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:36 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 320134
2022-03-10 10:39:36 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:36 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H1UBH5N5000181KT.html> (referer: https://war.163.com/)
2022-03-10 10:39:36 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H1UDQ4UR05504DOH.html"}
2022-03-10 10:39:37 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:37 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:39 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:39 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 251739
2022-03-10 10:39:39 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:39 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1UDQ4UR05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:39:39 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H218JNUD0514R9OJ.html"}
2022-03-10 10:39:40 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:40 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:42 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:42 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 247149
2022-03-10 10:39:42 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:42 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H218JNUD0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:42 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20LLOCV0514R9OJ.html"}
2022-03-10 10:39:42 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:42 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:44 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:44 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 147779
2022-03-10 10:39:44 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:44 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20LLOCV0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:44 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20M9DL80514R9OJ.html"}
2022-03-10 10:39:45 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:45 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:47 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:47 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 251076
2022-03-10 10:39:47 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:47 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20M9DL80514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:47 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20RNAA505504DOH.html"}
2022-03-10 10:39:48 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:48 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:50 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:50 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 247952
2022-03-10 10:39:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20RNAA505504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:39:50 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20S58SQ05504DOH.html"}
2022-03-10 10:39:51 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:51 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:53 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:53 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 250668
2022-03-10 10:39:53 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:53 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20S58SQ05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1U4MISN0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H1UBH5N5000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1UDQ4UR05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H218JNUD0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20LLOCV0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20M9DL80514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20RNAA505504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:39:53 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/war/article/H20SR4VD000181KT.html"}
2022-03-10 10:39:54 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:54 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:56 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:56 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 299989
2022-03-10 10:39:56 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:56 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H20SR4VD000181KT.html> (referer: https://war.163.com/)
2022-03-10 10:39:56 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20VCJV80514R9OJ.html"}
2022-03-10 10:39:57 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:39:57 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:59 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:39:59 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 204097
2022-03-10 10:39:59 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:39:59 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20VCJV80514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:39:59 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H20VECBG05504DOH.html"}
2022-03-10 10:40:01 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:01 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:03 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:03 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 215644
2022-03-10 10:40:03 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:03 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20VECBG05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:40:03 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H215IUIT0514R9OJ.html"}
2022-03-10 10:40:04 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:04 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:06 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:06 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 254732
2022-03-10 10:40:06 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:06 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H215IUIT0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:06 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H216PDOP0514R9OJ.html"}
2022-03-10 10:40:06 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:06 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:08 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:09 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 243467
2022-03-10 10:40:09 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:09 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H216PDOP0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:09 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/war/article/H21DEG4I000181KT.html"}
2022-03-10 10:40:10 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:12 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:12 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 304293
2022-03-10 10:40:12 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:12 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H21DEG4I000181KT.html> (referer: https://war.163.com/)
2022-03-10 10:40:12 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H2334UJK0514R9OJ.html"}
2022-03-10 10:40:13 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:15 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:15 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 236531
2022-03-10 10:40:15 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:15 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2334UJK0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:15 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H2367UL50514R9OJ.html"}
2022-03-10 10:40:16 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:16 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:18 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:18 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 131530
2022-03-10 10:40:18 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:18 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2367UL50514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:18 [scrapy.extensions.logstats] INFO: Crawled 38 pages (at 16 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20S58SQ05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H20SR4VD000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20VCJV80514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20VECBG05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H215IUIT0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H216PDOP0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2334UJK0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H21DEG4I000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:40:18 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H237UCF50514R9OJ.html"}
2022-03-10 10:40:19 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:21 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:21 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 231410
2022-03-10 10:40:21 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:21 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H237UCF50514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:21 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H21M3C8405504DOH.html"}
2022-03-10 10:40:22 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:22 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:24 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:24 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 250330
2022-03-10 10:40:24 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21M3C8405504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:40:24 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H21PT8AI05504DOH.html"}
2022-03-10 10:40:25 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:25 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:27 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:27 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 243013
2022-03-10 10:40:27 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21PT8AI05504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:40:27 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H21UEK1505504DOH.html"}
2022-03-10 10:40:27 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:27 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:29 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:29 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 200156
2022-03-10 10:40:29 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:29 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21UEK1505504DOH.html> (referer: https://war.163.com/)
2022-03-10 10:40:29 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H22UAQBN0514R9OJ.html"}
2022-03-10 10:40:30 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:30 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:32 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:32 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 234141
2022-03-10 10:40:32 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22UAQBN0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:32 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H2334U680514R9OJ.html"}
2022-03-10 10:40:33 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:33 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:35 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:35 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 233415
2022-03-10 10:40:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:35 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2334U680514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:35 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H233505K0514R9OJ.html"}
2022-03-10 10:40:36 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:36 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:38 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:38 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 253302
2022-03-10 10:40:38 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:38 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H233505K0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:38 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H236BKD20514R9OJ.html"}
2022-03-10 10:40:39 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:39 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:41 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:41 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 236994
2022-03-10 10:40:41 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H236BKD20514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2367UL50514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H237UCF50514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21M3C8405504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21PT8AI05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21UEK1505504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22UAQBN0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H233505K0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2334U680514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:41 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H237UBP90514R9OJ.html"}
2022-03-10 10:40:42 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:42 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:44 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:44 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 233595
2022-03-10 10:40:44 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:44 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H237UBP90514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:44 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://www.163.com/dy/article/H23956R40514R9OJ.html"}
2022-03-10 10:40:44 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:44 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:46 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:46 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 258036
2022-03-10 10:40:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H23956R40514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 10:40:46 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H236BKD20514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:46 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H237UBP90514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:46 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313504.html"}
2022-03-10 10:40:48 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:48 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:50 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:50 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 114590
2022-03-10 10:40:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313504.html> (referer: https://war.163.com/)
2022-03-10 10:40:50 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313506.html"}
2022-03-10 10:40:51 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:51 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:53 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:53 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 85178
2022-03-10 10:40:53 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:53 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313506.html> (referer: https://war.163.com/)
2022-03-10 10:40:53 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/url {"url": "https://war.163.com/photoview/4T8E0001/2313507.html"}
2022-03-10 10:40:53 [urllib3.connectionpool] DEBUG: http://localhost:64646 "POST /session/b41b3a22ce8794984c272013fb77086e/url HTTP/1.1" 200 14
2022-03-10 10:40:53 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:55 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e/source {}
2022-03-10 10:40:55 [urllib3.connectionpool] DEBUG: http://localhost:64646 "GET /session/b41b3a22ce8794984c272013fb77086e/source HTTP/1.1" 200 89073
2022-03-10 10:40:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313507.html> (referer: https://war.163.com/)
2022-03-10 10:40:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H23956R40514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 10:40:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313504.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:40:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313506.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:40:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313507.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 10:40:55 [scrapy.core.engine] INFO: Closing spider (finished)
2022-03-10 10:40:55 [selenium.webdriver.remote.remote_connection] DEBUG: DELETE http://localhost:64646/session/b41b3a22ce8794984c272013fb77086e {}
2022-03-10 10:40:55 [urllib3.connectionpool] DEBUG: http://localhost:64646 "DELETE /session/b41b3a22ce8794984c272013fb77086e HTTP/1.1" 200 14
2022-03-10 10:40:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 10:40:58 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 14119,
 'downloader/request_count': 52,
 'downloader/request_method_count/GET': 52,
 'downloader/response_bytes': 1442459,
 'downloader/response_count': 52,
 'downloader/response_status_count/200': 51,
 'downloader/response_status_count/301': 1,
 'elapsed_time_seconds': 170.620143,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 3, 10, 2, 40, 55, 792561),
 'httpcompression/response_bytes': 7446259,
 'httpcompression/response_count': 51,
 'log_count/DEBUG': 395,
 'log_count/ERROR': 50,
 'log_count/INFO': 12,
 'request_depth_max': 1,
 'response_received_count': 51,
 'scheduler/dequeued': 52,
 'scheduler/dequeued/memory': 52,
 'scheduler/enqueued': 52,
 'scheduler/enqueued/memory': 52,
 'spider_exceptions/AttributeError': 13,
 'spider_exceptions/TypeError': 37,
 'start_time': datetime.datetime(2022, 3, 10, 2, 38, 5, 172418)}
2022-03-10 10:40:58 [scrapy.core.engine] INFO: Spider closed (finished)
