2022-03-10 11:03:59 [scrapy.utils.log] INFO: Scrapy 2.5.1 started (bot: Crawl_hyx)
2022-03-10 11:03:59 [scrapy.utils.log] INFO: Versions: lxml 4.7.1.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.1.0, Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)], pyOpenSSL 22.0.0 (OpenSSL 1.1.1m  14 Dec 2021), cryptography 36.0.1, Platform Windows-10-10.0.19044-SP0
2022-03-10 11:03:59 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2022-03-10 11:03:59 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'Crawl_hyx',
 'LOG_FILE': 'log/scrapy_2022_3_10_4.log',
 'NEWSPIDER_MODULE': 'Crawl_hyx.spiders',
 'SPIDER_MODULES': ['Crawl_hyx.spiders']}
2022-03-10 11:03:59 [scrapy.extensions.telnet] INFO: Telnet Password: ace221360883a459
2022-03-10 11:03:59 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2022-03-10 11:03:59 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless", "--disable-gpu", "--no-sandbox", "--headless"]}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless", "--disable-gpu", "--no-sandbox", "--headless"]}}}
2022-03-10 11:03:59 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): localhost:50245
2022-03-10 11:04:00 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session HTTP/1.1" 200 797
2022-03-10 11:04:00 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:00 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/timeouts {"implicit": 1000}
2022-03-10 11:04:00 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/timeouts HTTP/1.1" 200 14
2022-03-10 11:04:00 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:00 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'Crawl_hyx.middlewares.CrawlHyxDownloaderMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-03-10 11:04:00 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-03-10 11:04:00 [scrapy.middleware] INFO: Enabled item pipelines:
['Crawl_hyx.pipelines.WanyiPipeline', 'Crawl_hyx.pipelines.ImagePipeline']
2022-03-10 11:04:00 [scrapy.core.engine] INFO: Spider opened
2022-03-10 11:04:00 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 11:04:00 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-03-10 11:04:00 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://war.163.com/> from <GET http://war.163.com/>
2022-03-10 11:04:00 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/"}
2022-03-10 11:04:02 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:04:02 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:04 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:04:04 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 440484
2022-03-10 11:04:04 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/> (referer: None)
2022-03-10 11:04:04 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/"}
2022-03-10 11:04:05 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:04:05 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:05 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "return document.body.scrollHeight;", "args": []}
2022-03-10 11:04:05 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 15
2022-03-10 11:04:05 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:07 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:07 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:09 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:09 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:09 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:11 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:11 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:11 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:13 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:13 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:15 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:15 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:15 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:17 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "window.scrollBy(0,1000)", "args": []}
2022-03-10 11:04:17 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 14
2022-03-10 11:04:17 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:17 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync {"script": "return document.body.scrollHeight;", "args": []}
2022-03-10 11:04:17 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/execute/sync HTTP/1.1" 200 15
2022-03-10 11:04:17 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:17 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313500.html"}
2022-03-10 11:04:19 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:04:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:21 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:04:21 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 132014
2022-03-10 11:04:21 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:21 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313500.html> (referer: https://war.163.com/)
2022-03-10 11:04:21 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H2367UL50514R9OJ.html"}
2022-03-10 11:04:22 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:04:22 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:24 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:04:24 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 118753
2022-03-10 11:04:24 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:04:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2367UL50514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:04:24 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H2334U680514R9OJ.html"}
2022-03-10 11:09:24 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 500 1117
2022-03-10 11:09:24 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:24 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H22UAQBN0514R9OJ.html"}
2022-03-10 11:09:26 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:26 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:28 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:28 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 225255
2022-03-10 11:09:28 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22UAQBN0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:28 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H236BKD20514R9OJ.html"}
2022-03-10 11:09:28 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:28 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:30 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:31 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 226257
2022-03-10 11:09:31 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:31 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H236BKD20514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:31 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313501.html"}
2022-03-10 11:09:31 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:31 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:33 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:33 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 135176
2022-03-10 11:09:33 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313501.html> (referer: https://war.163.com/)
2022-03-10 11:09:33 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H20T63UV000181KT.html"}
2022-03-10 11:09:35 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:37 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:37 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 303280
2022-03-10 11:09:37 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H20T63UV000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:09:37 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313502.html"}
2022-03-10 11:09:38 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:38 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:40 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:40 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 115134
2022-03-10 11:09:40 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:40 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313502.html> (referer: https://war.163.com/)
2022-03-10 11:09:40 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H22ILAC20514R9OJ.html"}
2022-03-10 11:09:41 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:41 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:43 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:43 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 185847
2022-03-10 11:09:43 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22ILAC20514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:43 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html"}
2022-03-10 11:09:43 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:43 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:45 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:46 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 236166
2022-03-10 11:09:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:46 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H2334UJK0514R9OJ.html"}
2022-03-10 11:09:46 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:48 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:48 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 236746
2022-03-10 11:09:48 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:48 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2334UJK0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:48 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313500.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:09:48 [scrapy.extensions.logstats] INFO: Crawled 11 pages (at 11 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 11:09:48 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.163.com/dy/article/H237UBP90514R9OJ.html> (failed 1 times): User timeout caused connection failure: Getting https://www.163.com/dy/article/H237UBP90514R9OJ.html took longer than 180.0 seconds..
2022-03-10 11:09:48 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://war.163.com/photoview/4T8E0001/2313497.html> (failed 1 times): User timeout caused connection failure: Getting https://war.163.com/photoview/4T8E0001/2313497.html took longer than 180.0 seconds..
2022-03-10 11:09:48 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://www.163.com/dy/article/H237UCF50514R9OJ.html> (failed 1 times): User timeout caused connection failure: Getting https://www.163.com/dy/article/H237UCF50514R9OJ.html took longer than 180.0 seconds..
2022-03-10 11:09:48 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.163.com/dy/article/H2334U680514R9OJ.html>
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\twisted\internet\defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: <200 https://www.163.com/dy/article/H2334U680514R9OJ.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\twisted\internet\defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\downloader\middleware.py", line 54, in process_response
    response = yield deferred_from_coro(method(request=request, response=response, spider=spider))
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\middlewares.py", line 70, in process_response
    bro.get(request.url)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.969
  (Session info: headless chrome=99.0.4844.51)
Stacktrace:
Backtrace:
	Ordinal0 [0x011269A3+2582947]
	Ordinal0 [0x010BA6D1+2139857]
	Ordinal0 [0x00FB3A98+1063576]
	Ordinal0 [0x00FA5727+1005351]
	Ordinal0 [0x00FA4727+1001255]
	Ordinal0 [0x00FA4AF7+1002231]
	Ordinal0 [0x00FAEF9F+1044383]
	Ordinal0 [0x00FB962B+1087019]
	Ordinal0 [0x00FBBD40+1097024]
	Ordinal0 [0x00FA4DF6+1002998]
	Ordinal0 [0x00FB94D5+1086677]
	Ordinal0 [0x01008616+1410582]
	Ordinal0 [0x00FF8366+1344358]
	Ordinal0 [0x00FD5176+1200502]
	Ordinal0 [0x00FD6066+1204326]
	GetHandleVerifier [0x012CBE02+1675858]
	GetHandleVerifier [0x0138036C+2414524]
	GetHandleVerifier [0x011BBB01+560977]
	GetHandleVerifier [0x011BA8D3+556323]
	Ordinal0 [0x010C020E+2163214]
	Ordinal0 [0x010C5078+2183288]
	Ordinal0 [0x010C51C0+2183616]
	Ordinal0 [0x010CEE1C+2223644]
	BaseThreadInitThunk [0x76DBFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77797A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77797A6E+238]

2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2367UL50514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22UAQBN0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H236BKD20514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313501.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H20T63UV000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313502.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22ILAC20514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H22TNAQQ0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2334UJK0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:09:49 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20LLOCV0514R9OJ.html"}
2022-03-10 11:09:50 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:52 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:52 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 147974
2022-03-10 11:09:52 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20LLOCV0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:09:52 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H21PT8AI05504DOH.html"}
2022-03-10 11:09:52 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:52 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:54 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:54 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 247760
2022-03-10 11:09:54 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21PT8AI05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:09:54 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H1UBH5N5000181KT.html"}
2022-03-10 11:09:56 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:56 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:58 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:09:58 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 327813
2022-03-10 11:09:58 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:09:58 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H1UBH5N5000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:09:58 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H23D74G405504DOH.html"}
2022-03-10 11:09:58 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:09:58 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:00 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:00 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 239268
2022-03-10 11:10:00 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:00 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H23D74G405504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:00 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H1UDQ4UR05504DOH.html"}
2022-03-10 11:10:02 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:02 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:04 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:04 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 250874
2022-03-10 11:10:04 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1UDQ4UR05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:04 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313498.html"}
2022-03-10 11:10:05 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:05 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:07 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:07 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 158223
2022-03-10 11:10:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:07 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313498.html> (referer: https://war.163.com/)
2022-03-10 11:10:07 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H218JNUD0514R9OJ.html"}
2022-03-10 11:10:07 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:07 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:09 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:10 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 247847
2022-03-10 11:10:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H218JNUD0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:10 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html"}
2022-03-10 11:10:10 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:12 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:12 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 263330
2022-03-10 11:10:12 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:12 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:12 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H21M3C8405504DOH.html"}
2022-03-10 11:10:13 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:15 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:15 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 251902
2022-03-10 11:10:15 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:15 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21M3C8405504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:15 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20LLOCV0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:15 [scrapy.extensions.logstats] INFO: Crawled 20 pages (at 9 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 11:10:15 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20M9DL80514R9OJ.html"}
2022-03-10 11:10:16 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:16 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:18 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:18 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 251823
2022-03-10 11:10:18 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:18 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20M9DL80514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:18 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20RNAA505504DOH.html"}
2022-03-10 11:10:19 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:21 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:21 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 248566
2022-03-10 11:10:21 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:21 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20RNAA505504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21PT8AI05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H1UBH5N5000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H23D74G405504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1UDQ4UR05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313498.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H218JNUD0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1T7B6BO0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:21 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20S58SQ05504DOH.html"}
2022-03-10 11:10:22 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:22 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:24 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:24 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 250937
2022-03-10 11:10:24 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20S58SQ05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:24 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H20SR4VD000181KT.html"}
2022-03-10 11:10:25 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:25 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:27 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:27 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 301025
2022-03-10 11:10:27 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H20SR4VD000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:10:27 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20VCJV80514R9OJ.html"}
2022-03-10 11:10:28 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:28 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:30 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:30 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 205302
2022-03-10 11:10:30 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:30 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20VCJV80514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:30 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20VECBG05504DOH.html"}
2022-03-10 11:10:31 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:31 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:33 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:33 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 225685
2022-03-10 11:10:33 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20VECBG05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:33 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H215IUIT0514R9OJ.html"}
2022-03-10 11:10:34 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:34 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:36 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:36 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 256383
2022-03-10 11:10:36 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:36 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H215IUIT0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:36 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H216PDOP0514R9OJ.html"}
2022-03-10 11:10:37 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:37 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:39 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:39 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 242873
2022-03-10 11:10:39 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:39 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H216PDOP0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21M3C8405504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20M9DL80514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20RNAA505504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20S58SQ05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H20SR4VD000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20VECBG05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20VCJV80514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H215IUIT0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:10:39 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H1V4J10B05504DOH.html"}
2022-03-10 11:10:40 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:40 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:42 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:42 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 256637
2022-03-10 11:10:42 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:42 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1V4J10B05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:10:42 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20J6EVG0514R9OJ.html"}
2022-03-10 11:10:42 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:42 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:44 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:45 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 255443
2022-03-10 11:10:45 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:45 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20J6EVG0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:45 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H21DEG4I000181KT.html"}
2022-03-10 11:10:46 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:48 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:48 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 302918
2022-03-10 11:10:48 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:48 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H21DEG4I000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:10:48 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H21DGSJI000181KT.html"}
2022-03-10 11:10:49 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:49 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:51 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:51 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 304491
2022-03-10 11:10:51 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:51 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H21DGSJI000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:10:51 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20KD22N0514R9OJ.html"}
2022-03-10 11:10:52 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:52 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:54 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:54 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 260520
2022-03-10 11:10:54 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20KD22N0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:10:54 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313504.html"}
2022-03-10 11:10:55 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:10:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:57 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:10:57 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 118517
2022-03-10 11:10:57 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:10:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313504.html> (referer: https://war.163.com/)
2022-03-10 11:10:57 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20NED830514R9OJ.html"}
2022-03-10 11:11:08 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:08 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:10 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:10 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 253246
2022-03-10 11:11:10 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20NED830514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:10 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20NEDKS0514R9OJ.html"}
2022-03-10 11:11:11 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:11 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:13 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:13 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 258709
2022-03-10 11:11:13 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:13 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20NEDKS0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:13 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H20S7UTJ05504DOH.html"}
2022-03-10 11:11:14 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:14 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:16 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:16 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 247896
2022-03-10 11:11:16 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:16 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H20S7UTJ05504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:11:17 [scrapy.extensions.logstats] INFO: Crawled 37 pages (at 17 pages/min), scraped 0 items (at 0 items/min)
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H216PDOP0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1V4J10B05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20J6EVG0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H21DEG4I000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H21DGSJI000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20KD22N0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313504.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20NED830514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20NEDKS0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:17 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313507.html"}
2022-03-10 11:11:17 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:17 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:19 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:19 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 89045
2022-03-10 11:11:19 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:19 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313507.html> (referer: https://war.163.com/)
2022-03-10 11:11:19 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H20S7UTJ05504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:19 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313506.html"}
2022-03-10 11:11:20 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:20 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:22 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:22 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 85150
2022-03-10 11:11:22 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:22 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313506.html> (referer: https://war.163.com/)
2022-03-10 11:11:22 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://war.163.com/photoview/4T8E0001/2313497.html"}
2022-03-10 11:11:23 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:23 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:25 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:25 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 140952
2022-03-10 11:11:25 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://war.163.com/photoview/4T8E0001/2313497.html> (referer: https://war.163.com/)
2022-03-10 11:11:25 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H1VHH5V105504DOH.html"}
2022-03-10 11:11:26 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:26 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:28 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:29 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 247573
2022-03-10 11:11:29 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:29 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H1VHH5V105504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:11:29 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H23FVJC8000181KT.html"}
2022-03-10 11:11:30 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:30 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:32 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:32 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 287432
2022-03-10 11:11:32 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H23FVJC8000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:11:32 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H233505K0514R9OJ.html"}
2022-03-10 11:11:33 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:33 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:35 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:35 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 258327
2022-03-10 11:11:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:35 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H233505K0514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:35 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H212CHE805504DOH.html"}
2022-03-10 11:11:36 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:36 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:38 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:38 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 255585
2022-03-10 11:11:38 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:38 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H212CHE805504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:11:38 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H23956R40514R9OJ.html"}
2022-03-10 11:11:38 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:38 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:40 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:40 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 267162
2022-03-10 11:11:40 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:40 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H23956R40514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:40 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H21UEK1505504DOH.html"}
2022-03-10 11:11:41 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:41 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:43 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:43 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 202290
2022-03-10 11:11:43 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H21UEK1505504DOH.html> (referer: https://war.163.com/)
2022-03-10 11:11:43 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/war/article/H23FT7BC000181KT.html"}
2022-03-10 11:11:44 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:44 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:46 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:46 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 263922
2022-03-10 11:11:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/war/article/H23FT7BC000181KT.html> (referer: https://war.163.com/)
2022-03-10 11:11:46 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H2117GQ00514R9OJ.html"}
2022-03-10 11:11:47 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:47 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:49 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:49 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 250390
2022-03-10 11:11:49 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:49 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H2117GQ00514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313507.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313506.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://war.163.com/photoview/4T8E0001/2313497.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H1VHH5V105504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H23FVJC8000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H233505K0514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H212CHE805504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H23956R40514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H21UEK1505504DOH.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/war/article/H23FT7BC000181KT.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 103, in parse_detail
    pubTime = pubTime.replace('\n', '')
AttributeError: 'NoneType' object has no attribute 'replace'
2022-03-10 11:11:50 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H237UCF50514R9OJ.html"}
2022-03-10 11:11:50 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:50 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:52 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:52 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 234397
2022-03-10 11:11:52 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H237UCF50514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:52 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/url {"url": "https://www.163.com/dy/article/H237UBP90514R9OJ.html"}
2022-03-10 11:11:53 [urllib3.connectionpool] DEBUG: http://localhost:50245 "POST /session/c8dd7b2a3084214dbfb889d30b8dd2e9/url HTTP/1.1" 200 14
2022-03-10 11:11:53 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:55 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9/source {}
2022-03-10 11:11:55 [urllib3.connectionpool] DEBUG: http://localhost:50245 "GET /session/c8dd7b2a3084214dbfb889d30b8dd2e9/source HTTP/1.1" 200 233440
2022-03-10 11:11:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.163.com/dy/article/H237UBP90514R9OJ.html> (referer: https://war.163.com/)
2022-03-10 11:11:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H2117GQ00514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H237UCF50514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.163.com/dy/article/H237UBP90514R9OJ.html> (referer: https://war.163.com/)
Traceback (most recent call last):
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python\Crawler_hyx\venv\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "D:\Python\Crawler_hyx\Crawl_hyx\Crawl_hyx\spiders\wanyi.py", line 152, in parse_detail
    num = int(num)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-03-10 11:11:55 [scrapy.core.engine] INFO: Closing spider (finished)
2022-03-10 11:11:55 [selenium.webdriver.remote.remote_connection] DEBUG: DELETE http://localhost:50245/session/c8dd7b2a3084214dbfb889d30b8dd2e9 {}
2022-03-10 11:11:55 [urllib3.connectionpool] DEBUG: http://localhost:50245 "DELETE /session/c8dd7b2a3084214dbfb889d30b8dd2e9 HTTP/1.1" 200 14
2022-03-10 11:11:55 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2022-03-10 11:11:58 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 3,
 'downloader/request_bytes': 14942,
 'downloader/request_count': 55,
 'downloader/request_method_count/GET': 55,
 'downloader/response_bytes': 1451751,
 'downloader/response_count': 52,
 'downloader/response_status_count/200': 51,
 'downloader/response_status_count/301': 1,
 'elapsed_time_seconds': 475.320818,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 3, 10, 3, 11, 55, 777205),
 'httpcompression/response_bytes': 7470247,
 'httpcompression/response_count': 51,
 'log_count/DEBUG': 394,
 'log_count/ERROR': 50,
 'log_count/INFO': 13,
 'request_depth_max': 1,
 'response_received_count': 50,
 'retry/count': 3,
 'retry/reason_count/twisted.internet.error.TimeoutError': 3,
 'scheduler/dequeued': 55,
 'scheduler/dequeued/memory': 55,
 'scheduler/enqueued': 55,
 'scheduler/enqueued/memory': 55,
 'spider_exceptions/AttributeError': 15,
 'spider_exceptions/TypeError': 34,
 'start_time': datetime.datetime(2022, 3, 10, 3, 4, 0, 456387)}
2022-03-10 11:11:58 [scrapy.core.engine] INFO: Spider closed (finished)
